/*
 * Copyright (C) 2021 - 2025, Stephan Mueller <smueller@chronox.de>
 *
 * License: see LICENSE file in root directory
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF
 * WHICH ARE HEREBY DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE, EVEN IF NOT ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#include "lc_sha3.h"
#include "visibility.h"

LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_sha3_224) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_sha3_256) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_sha3_384) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_sha3_512) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_shake128) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_shake256) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_shake512) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_cshake128) = NULL;
LC_INTERFACE_SYMBOL(const struct lc_hash *, lc_cshake256) = NULL;
