################################################################################
# Signature implementation: Dilithium

ccflags-$(CONFIG_LEANCRYPTO_DILITHIUM)					       \
				+= -I$(PWD)/../signature/api
asflags-$(CONFIG_LEANCRYPTO_DILITHIUM)					       \
				+= -I$(PWD)

################################################################################
# C Implementation
################################################################################
# Dilithium Common
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM)				       \
				+= ../signature/src/dilithium_zetas.o

# Dilithium 87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_87)				       \
				+= ../signature/src/dilithium_ntt.o	       \
				   ../signature/src/dilithium_poly.o	       \
				   ../signature/src/dilithium_rounding.o       \
				   ../signature/src/dilithium_selftest.o       \
				   ../signature/src/dilithium_signature_c.o    \
				   leancrypto_kernel_dilithium.o

# Dilithium 65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_65)				       \
				+= dilithium65/dilithium_ntt.o		       \
				   dilithium65/dilithium_poly.o		       \
				   dilithium65/dilithium_rounding.o	       \
				   dilithium65/dilithium_selftest.o	       \
				   dilithium65/dilithium_signature_c.o	       \
				   dilithium65/leancrypto_kernel_dilithium.o
CFLAGS_dilithium65/dilithium_ntt.o			:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/dilithium_poly.o			:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/dilithium_rounding.o			:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/dilithium_selftest.o			:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/dilithium_signature_c.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/leancrypto_kernel_dilithium.o	:= -DLC_DILITHIUM_TYPE_65

# Dilithium 44
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_44)				       \
				+= dilithium44/dilithium_ntt.o		       \
				   dilithium44/dilithium_poly.o		       \
				   dilithium44/dilithium_rounding.o	       \
				   dilithium44/dilithium_selftest.o	       \
				   dilithium44/dilithium_signature_api_c.o     \
				   dilithium44/dilithium_signature_c.o	       \
				   dilithium44/leancrypto_kernel_dilithium.o
CFLAGS_dilithium44/dilithium_ntt.o			:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/dilithium_poly.o			:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/dilithium_rounding.o			:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/dilithium_selftest.o			:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/dilithium_signature_api_c.o		:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/dilithium_signature_c.o		:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/leancrypto_kernel_dilithium.o	:= -DLC_DILITHIUM_TYPE_44

# Dilithium-87-ED25519 implementation
ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_ED25519)			       \
				+= ../signature/src/dilithium_ed25519_signature.o\
				   leancrypto_kernel_dilithium_ed25519.o
endif

# Dilithium-65-ED25519 implementation
ifdef CONFIG_LEANCRYPTO_DILITHIUM_65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_ED25519)			       \
				+= dilithium65/dilithium_ed25519_signature.o   \
				   dilithium65/leancrypto_kernel_dilithium_ed25519.o
CFLAGS_dilithium65/dilithium_ed25519_signature.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/leancrypto_kernel_dilithium_ed25519.o:= -DLC_DILITHIUM_TYPE_65
endif

# Dilithium-44-ED25519 implementation
ifdef CONFIG_LEANCRYPTO_DILITHIUM_44
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_ED25519)			       \
				+= dilithium44/dilithium_ed25519_signature.o   \
				   dilithium44/leancrypto_kernel_dilithium_ed25519.o
CFLAGS_dilithium44/dilithium_ed25519_signature.o	:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/leancrypto_kernel_dilithium_ed25519.o:= -DLC_DILITHIUM_TYPE_44
endif

ifdef CONFIG_X86_64

################################################################################
# AVX2 Implementation
################################################################################
# Dilithium Common
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM)				       \
			+= ../signature/src/avx2/dilithium_consts_avx2.o       \

# Dilithium 87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_87)				       \
			+= ../signature/src/avx2/dilithium_invntt_avx2.o       \
			   ../signature/src/avx2/dilithium_ntt_avx2.o	       \
			   ../signature/src/avx2/dilithium_pointwise_avx2.o    \
			   ../signature/src/avx2/dilithium_poly_avx2.o	       \
			   ../signature/src/avx2/dilithium_polyvec_avx2.o      \
			   ../signature/src/avx2/dilithium_rejsample_avx2.o    \
			   ../signature/src/avx2/dilithium_rounding_avx2.o     \
			   ../signature/src/avx2/dilithium_signature_api_avx2.o\
			   ../signature/src/avx2/dilithium_signature_avx2.o    \
			   ../signature/src/avx2/dilithium_shuffle_avx2.o

# Dilithium 65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_65)				       \
			+= dilithium65/avx2/dilithium_invntt_avx2.o	       \
			   dilithium65/avx2/dilithium_ntt_avx2.o	       \
			   dilithium65/avx2/dilithium_pointwise_avx2.o	       \
			   dilithium65/avx2/dilithium_poly_avx2.o	       \
			   dilithium65/avx2/dilithium_polyvec_avx2.o	       \
			   dilithium65/avx2/dilithium_rejsample_avx2.o	       \
			   dilithium65/avx2/dilithium_rounding_avx2.o	       \
			   dilithium65/avx2/dilithium_signature_api_avx2.o     \
			   dilithium65/avx2/dilithium_signature_avx2.o	       \
			   dilithium65/avx2/dilithium_shuffle_avx2.o
AFLAGS_dilithium65/avx2/dilithium_invntt_avx2.o		:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/avx2/dilithium_ntt_avx2.o		:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/avx2/dilithium_pointwise_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_poly_avx2.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_polyvec_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_rejsample_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_rounding_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_signature_api_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/avx2/dilithium_signature_avx2.o	:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/avx2/dilithium_shuffle_avx2.o	:= -DLC_DILITHIUM_TYPE_65

else ifdef CONFIG_ARM

################################################################################
# ARMv7 Implementation
################################################################################
# Dilithium Common
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM)				       \
			+= ../signature/src/armv7/dilithium_ntt_consts.o

# Dilithium 87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_87)				       \
			+= ../signature/src/armv7/dilithium_ntt_armv7.o	       \
			   ../signature/src/armv7/dilithium_pointwise_smull_armv7.o\
			   ../signature/src/armv7/dilithium_poly_armv7.o       \
			   ../signature/src/armv7/dilithium_poly.o	       \
			   ../signature/src/armv7/dilithium_signature_api_armv7.o\
			   ../signature/src/armv7/dilithium_signature_armv7.o

# Dilithium 65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_65)				       \
			+= dilithium65/armv7/dilithium_ntt_armv7.o	       \
			   dilithium65/armv7/dilithium_pointwise_smull_armv7.o \
			   dilithium65/armv7/dilithium_poly_armv7.o	       \
			   dilithium65/armv7/dilithium_poly.o		       \
			   dilithium65/armv7/dilithium_signature_api_armv7.o   \
			   dilithium65/armv7/dilithium_signature_armv7.o

AFLAGS_dilithium65/armv7/dilithium_ntt_armv7.o		:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/armv7/dilithium_pointwise_smull_armv7.o:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/armv7/dilithium_poly_armv7.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/armv7/dilithium_poly.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/armv7/dilithium_signature_api_armv7.o:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/armv7/dilithium_signature_armv7.o	:= -DLC_DILITHIUM_TYPE_65

else ifdef CONFIG_ARM64

################################################################################
# ARMv8 Implementation
################################################################################
# Dilithium Common
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM)				       \
			+= ../signature/src/armv8/NTT_params.o

# Dilithium 87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_87)				       \
			+= ../signature/src/armv8/dilithium_intt_armv8.o       \
			   ../signature/src/armv8/dilithium_ntt_armv8.o	       \
			   ../signature/src/armv8/dilithium_poly_armv8.o       \
			   ../signature/src/armv8/dilithium_signature_api_armv8.o\
			   ../signature/src/armv8/dilithium_signature_armv8.o

# Dilithium 65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_65)				       \
			+= dilithium65/armv8/dilithium_intt_armv8.o	       \
			   dilithium65/armv8/dilithium_ntt_armv8.o	       \
			   dilithium65/armv8/dilithium_poly_armv8.o	       \
			   dilithium65/armv8/dilithium_signature_api_armv8.o   \
			   dilithium65/armv8/dilithium_signature_armv8.o
AFLAGS_dilithium65/armv8/dilithium_intt_armv8.o		:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/armv8/dilithium_ntt_armv8.o		:= -DLC_DILITHIUM_TYPE_65
AFLAGS_dilithium65/armv8/dilithium_poly_armv8.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/armv8/dilithium_signature_api_armv8.o:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/armv8/dilithium_signature_armv8.o	:= -DLC_DILITHIUM_TYPE_65


################################################################################
# Interfaces for any non-accelerated implementation
################################################################################
else

# Dilithium 87
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_87)				       \
			+= ../signature/src/dilithium_signature_api_c.o

# Dilithium 65
leancrypto-$(CONFIG_LEANCRYPTO_DILITHIUM_65)				       \
			+= dilithium65/dilithium_signature_api_c.o
CFLAGS_dilithium65/dilithium_signature_api_c.o		:= -DLC_DILITHIUM_TYPE_65

# Dilithium 44 is already covered by the C implementation definition

endif

################################################################################
# Dilithium Test Cases
################################################################################
ccflags-$(CONFIG_LEANCRYPTO_DILITHIUM)					       \
				+= -I$(PWD)/../signature/src
ifdef CONFIG_LEANCRYPTO_DILITHIUM
ccflags-y			+= -DCONFIG_LEANCRYPTO_DILITHIUM

ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
ccflags-y			+= -DCONFIG_LEANCRYPTO_DILITHIUM_87
obj-m				+= leancrypto_kernel_dilithium_87_tester.o

obj-m		  		+= dilithium_tester_c.o
obj-m		  		+= dilithium_tester_common.o
obj-m		  		+= dilithium_invalid_tester.o

dilithium_tester_c-y		+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_c.o     \
				   ../drng/src/selftest_rng.o

dilithium_tester_common-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_common.o\
				   ../drng/src/selftest_rng.o

dilithium_invalid_tester-y	+= ../signature/tests/dilithium_invalid_tester.o
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_65
ccflags-y			+= -DCONFIG_LEANCRYPTO_DILITHIUM_65
obj-m				+= leancrypto_kernel_dilithium_65_tester.o

obj-m		  		+= dilithium_65_tester_c.o
obj-m		  		+= dilithium_65_tester_common.o
obj-m		  		+= dilithium_65_invalid_tester.o

dilithium_65_tester_c-y		+= dilithium65/tests/dilithium_tester.o	       \
				   dilithium65/tests/dilithium_tester_c.o      \
				   ../drng/src/selftest_rng.o

dilithium_65_tester_common-y	+= dilithium65/tests/dilithium_tester.o	       \
				   dilithium65/tests/dilithium_tester_common.o \
				   ../drng/src/selftest_rng.o

dilithium_65_invalid_tester-y	+= dilithium65/tests/dilithium_invalid_tester.o

CFLAGS_leancrypto_kernel_dilithium_65_tester.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_c.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_common.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_invalid_tester.o	:= -DLC_DILITHIUM_TYPE_65
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_44
ccflags-y			+= -DCONFIG_LEANCRYPTO_DILITHIUM_44
obj-m				+= leancrypto_kernel_dilithium_44_tester.o

obj-m		  		+= dilithium_44_tester_c.o
obj-m		  		+= dilithium_44_tester_common.o
obj-m		  		+= dilithium_44_invalid_tester.o

dilithium_44_tester_c-y		+= dilithium44/tests/dilithium_tester.o	       \
				   dilithium44/tests/dilithium_tester_c.o      \
				   ../drng/src/selftest_rng.o

dilithium_44_tester_common-y	+= dilithium44/tests/dilithium_tester.o	       \
				   dilithium44/tests/dilithium_tester_common.o \
				   ../drng/src/selftest_rng.o

dilithium_44_invalid_tester-y	+= dilithium44/tests/dilithium_invalid_tester.o

CFLAGS_leancrypto_kernel_dilithium_44_tester.o		:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/tests/dilithium_tester.o		:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/tests/dilithium_tester_c.o		:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/tests/dilithium_tester_common.o	:= -DLC_DILITHIUM_TYPE_44
CFLAGS_dilithium44/tests/dilithium_invalid_tester.o	:= -DLC_DILITHIUM_TYPE_44
endif

ifdef CONFIG_X86_64
ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
obj-m				+= dilithium_tester_avx2.o
obj-m				+= dilithium_tester_iuf_avx2.o

dilithium_tester_avx2-y		+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_avx2.o  \
				   ../drng/src/selftest_rng.o
dilithium_tester_iuf_avx2-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_iuf_avx2.o\
				   ../drng/src/selftest_rng.o
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_65
obj-m				+= dilithium_65_tester_avx2.o
obj-m				+= dilithium_65_tester_iuf_avx2.o

dilithium_65_tester_avx2-y	+= dilithium65/tests/dilithium_tester.o	       \
				   dilithium65/tests/dilithium_tester_avx2.o   \
				   ../drng/src/selftest_rng.o
dilithium_65_tester_iuf_avx2-y	+= dilithium65/tests/dilithium_tester.o	       \
				   dilithium65/tests/dilithium_tester_iuf_avx2.o\
				   ../drng/src/selftest_rng.o
CFLAGS_dilithium65/tests/dilithium_tester.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_avx2.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_iuf_avx2.o	:= -DLC_DILITHIUM_TYPE_65
endif
endif

ifdef CONFIG_ARM64
ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
obj-m				+= dilithium_tester_armv8.o
obj-m				+= dilithium_tester_iuf_armv8.o

dilithium_tester_armv8-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_armv8.o \
				   ../drng/src/selftest_rng.o
dilithium_tester_iuf_armv8-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_iuf_armv8.o\
				   ../drng/src/selftest_rng.o
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
obj-m				+= dilithium_65_tester_armv8.o
obj-m				+= dilithium_65_tester_iuf_armv8.o

dilithium_65_tester_armv8-y	+= dilithium65/tests/dilithium_tester.o       \
				   dilithium65/tests/dilithium_tester_armv8.o \
				   ../drng/src/selftest_rng.o
dilithium_65_tester_iuf_armv8-y	+= dilithium65/tests/dilithium_tester.o       \
				   dilithium65/tests/dilithium_tester_iuf_armv8.o\
				   ../drng/src/selftest_rng.o
CFLAGS_dilithium65/tests/dilithium_tester.o		:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_armv8.o	:= -DLC_DILITHIUM_TYPE_65
CFLAGS_dilithium65/tests/dilithium_tester_iuf_armv8.o	:= -DLC_DILITHIUM_TYPE_65
endif
endif

ifdef CONFIG_ARM
obj-m				+= dilithium_tester_armv7.o
obj-m				+= dilithium_tester_iuf_armv7.o

dilithium_tester_armv7-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_armv7.o \
				   ../drng/src/selftest_rng.o
dilithium_tester_iuf_armv7-y	+= ../signature/tests/dilithium_tester.o       \
				   ../signature/tests/dilithium_tester_iuf_armv7.o\
				   ../drng/src/selftest_rng.o
endif

endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_ED25519
ccflags-y			+= -DCONFIG_LEANCRYPTO_DILITHIUM_ED25519

ifdef CONFIG_LEANCRYPTO_DILITHIUM_87
obj-m		  		+= dilithium_ed25519_tester.o

dilithium_ed25519_tester-y	+= ../signature/tests/dilithium_ed25519_tester.o\
				   ../drng/src/selftest_rng.o
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_65
obj-m		  		+= dilithium_65_ed25519_tester.o

dilithium_65_ed25519_tester-y	+= dilithium65/tests/dilithium_ed25519_tester.o\
				   ../drng/src/selftest_rng.o
CFLAGS_dilithium65/tests/dilithium_ed25519_tester.o	:= -DLC_DILITHIUM_TYPE_65
endif

ifdef CONFIG_LEANCRYPTO_DILITHIUM_44
obj-m		  		+= dilithium_44_ed25519_tester.o

dilithium_44_ed25519_tester-y	+= dilithium44/tests/dilithium_ed25519_tester.o\
				   ../drng/src/selftest_rng.o
CFLAGS_dilithium44/tests/dilithium_ed25519_tester.o	:= -DLC_DILITHIUM_TYPE_44
endif

endif
