/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for authenticode_SpcIndirectDataContent
 */
#pragma once
#include "asn1_encoder.h"
#include "asn1_decoder.h"

// clang-format off
extern const struct lc_asn1_encoder lc_authenticode_SpcIndirectDataContent_encoder;
extern const struct lc_asn1_decoder lc_authenticode_SpcIndirectDataContent_decoder;

extern int lc_spc_attribute_type_OID_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_spc_attribute_type_OID(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_spc_digest_algorithm_OID_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_spc_digest_algorithm_OID(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_spc_file_digest_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_spc_file_digest(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_spc_pe_image_data_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_spc_pe_image_data(void *, size_t, unsigned char, const uint8_t *, size_t);
// clang-format on
