/*
 * Copyright (C) 2020 - 2024, Stephan Mueller <smueller@chronox.de>
 *
 * License: see LICENSE file in root directory
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF
 * WHICH ARE HEREBY DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE, EVEN IF NOT ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#include "compare.h"
#include "lc_ascon_hash.h"
#include "visibility.h"

#include "ascon_avx512.h"
#include "ascon_arm_neon.h"
#include "ascon_c.h"

#define LC_EXEC_ONE_TEST(ascon_impl)                                           \
	if (ascon_impl)                                                        \
	ret += ascon_128a_tester(ascon_impl, #ascon_impl)

static int ascon_128a_tester(const struct lc_hash *ascon, const char *name)
{
	/*
	 * Vector 5 from genkat_crypto_hash_asconhashav12_ref generated by code
	 * https://github.com/ascon/ascon-c
	 */
	static const uint8_t msg[] = { 0x00, 0x01, 0x02, 0x03 };
	static const uint8_t exp[] = { 0x7B, 0x4B, 0xD4, 0xD5, 0x73, 0x19, 0x66,
				       0x01, 0x0E, 0xA4, 0xF5, 0xF3, 0x6C, 0x74,
				       0x36, 0x11, 0x0C, 0x64, 0x19, 0x07, 0xD1,
				       0x2A, 0x1F, 0x12, 0x16, 0x92, 0x2D, 0xEB,
				       0xD6, 0x1B, 0x13, 0xFE };
	uint8_t act[LC_ASCON_HASH_DIGESTSIZE];
	int ret;
	LC_ASCON_CTX_ON_STACK(ascon_stack, ascon);

	printf("hash ctx %s (%s implementation) len %lu\n", name,
	       ascon == lc_ascon_128a_c ? "C" : "accelerated",
	       LC_HASH_CTX_SIZE(ascon));

	lc_hash(ascon, msg, sizeof(msg), act);
	ret = lc_compare(act, exp, sizeof(act), "Ascon 128a");

	lc_hash_init(ascon_stack);
	lc_hash_update(ascon_stack, msg, sizeof(msg));
	lc_hash_final(ascon_stack, act);
	lc_hash_zero(ascon_stack);
	ret += lc_compare(act, exp, sizeof(act), "Ascon 128a stack");

	return ret;
}

LC_TEST_FUNC(int, main, int argc, char *argv[])
{
	int ret = 0;
	(void)argc;
	(void)argv;

	LC_EXEC_ONE_TEST(lc_ascon_128a);
	LC_EXEC_ONE_TEST(lc_ascon_128a_c);
	LC_EXEC_ONE_TEST(lc_ascon_128a_avx512);
	LC_EXEC_ONE_TEST(lc_ascon_128a_arm_neon);

	return ret;
}
