
/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for eddsa_curve_private_key
 */
#include "asn1_ber_bytecode.h"
#include "eddsa_curve_private_key_asn1.h"

// clang-format off

enum eddsa_curve_private_key_actions {
	ACT_lc_x509_eddsa_private_key = 0,
	NR__eddsa_curve_private_key_actions = 1
};

static const asn1_action_t eddsa_curve_private_key_action_table[NR__eddsa_curve_private_key_actions] = {
	[   0] = lc_x509_eddsa_private_key,
};

static const asn1_action_enc_t eddsa_curve_private_key_action_table_enc[NR__eddsa_curve_private_key_actions] = {
	[   0] = lc_x509_eddsa_private_key_enc,
};

static const unsigned char eddsa_curve_private_key_machine[] = {
	// CurvePrivateKey
	[   0] = ASN1_OP_MATCH_ACT,
	[   1] = _tag(UNIV, PRIM, OTS),
	[   2] = _action(ACT_lc_x509_eddsa_private_key),
	[   3] = ASN1_OP_COMPLETE,
};

const struct lc_asn1_decoder lc_eddsa_curve_private_key_decoder = {
	.machine = eddsa_curve_private_key_machine,
	.machlen = sizeof(eddsa_curve_private_key_machine),
	.actions = eddsa_curve_private_key_action_table,
};

const struct lc_asn1_encoder lc_eddsa_curve_private_key_encoder = {
	.machine = eddsa_curve_private_key_machine,
	.machlen = sizeof(eddsa_curve_private_key_machine),
	.actions = eddsa_curve_private_key_action_table_enc,
};

// clang-format on
