/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for eddsa_curve_private_key
 */
#pragma once
#include "asn1_encoder.h"
#include "asn1_decoder.h"

// clang-format off
extern const struct lc_asn1_encoder lc_eddsa_curve_private_key_encoder;
extern const struct lc_asn1_decoder lc_eddsa_curve_private_key_decoder;

extern int lc_x509_eddsa_private_key_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_eddsa_private_key(void *, size_t, unsigned char, const uint8_t *, size_t);
// clang-format on
