/*
 * Automatically generated by asn1/src/build_OID_registry.  Do not edit
 */
// clang-format off

static const unsigned short oid_index[OID__NR + 1] = {
	[OID_id_dsa_with_sha1] = 0,
	[OID_id_dsa] = 7,
	[OID_id_ecPublicKey] = 14,
	[OID_id_prime192v1] = 21,
	[OID_id_prime256v1] = 29,
	[OID_id_ecdsa_with_sha1] = 37,
	[OID_id_ecdsa_with_sha224] = 44,
	[OID_id_ecdsa_with_sha256] = 52,
	[OID_id_ecdsa_with_sha384] = 60,
	[OID_id_ecdsa_with_sha512] = 68,
	[OID_rsaEncryption] = 76,
	[OID_sha1WithRSAEncryption] = 85,
	[OID_sha256WithRSAEncryption] = 94,
	[OID_sha384WithRSAEncryption] = 103,
	[OID_sha512WithRSAEncryption] = 112,
	[OID_sha224WithRSAEncryption] = 121,
	[OID_data] = 130,
	[OID_signed_data] = 139,
	[OID_email_address] = 148,
	[OID_contentType] = 157,
	[OID_messageDigest] = 166,
	[OID_signingTime] = 175,
	[OID_smimeCapabilites] = 184,
	[OID_smimeAuthenticatedAttrs] = 193,
	[OID_mskrb5] = 204,
	[OID_krb5] = 213,
	[OID_krb5u2u] = 222,
	[OID_msIndirectData] = 232,
	[OID_msStatementType] = 242,
	[OID_msSpOpusInfo] = 252,
	[OID_msPeImageDataObjId] = 262,
	[OID_msIndividualSPKeyPurpose] = 272,
	[OID_msOutlookExpress] = 282,
	[OID_ntlmssp] = 291,
	[OID_negoex] = 301,
	[OID_spnego] = 311,
	[OID_IAKerb] = 317,
	[OID_PKU2U] = 323,
	[OID_Scram] = 329,
	[OID_certAuthInfoAccess] = 335,
	[OID_sha1] = 343,
	[OID_id_ansip384r1] = 348,
	[OID_id_ansip521r1] = 353,
	[OID_sha256] = 358,
	[OID_sha384] = 367,
	[OID_sha512] = 376,
	[OID_sha224] = 385,
	[OID_commonName] = 394,
	[OID_surname] = 397,
	[OID_countryName] = 400,
	[OID_locality] = 403,
	[OID_stateOrProvinceName] = 406,
	[OID_organizationName] = 409,
	[OID_organizationUnitName] = 412,
	[OID_title] = 415,
	[OID_description] = 418,
	[OID_name] = 421,
	[OID_givenName] = 424,
	[OID_initials] = 427,
	[OID_generationalQualifier] = 430,
	[OID_subjectKeyIdentifier] = 433,
	[OID_keyUsage] = 436,
	[OID_subjectAltName] = 439,
	[OID_issuerAltName] = 442,
	[OID_basicConstraints] = 445,
	[OID_crlDistributionPoints] = 448,
	[OID_certPolicies] = 451,
	[OID_authorityKeyIdentifier] = 454,
	[OID_extKeyUsage] = 457,
	[OID_anyExtendedKeyUsage] = 460,
	[OID_id_kp_serverAuth] = 464,
	[OID_id_kp_clientAuth] = 472,
	[OID_id_kp_codeSigning] = 480,
	[OID_id_kp_emailProtection] = 488,
	[OID_id_kp_timeStamping] = 496,
	[OID_id_kp_OCSPSigning] = 504,
	[OID_id_kp_ModuleSigning] = 512,
	[OID_NetlogonMechanism] = 522,
	[OID_appleLocalKdcSupported] = 528,
	[OID_gostCPSignA] = 534,
	[OID_gostCPSignB] = 541,
	[OID_gostCPSignC] = 548,
	[OID_gost2012PKey256] = 555,
	[OID_gost2012PKey512] = 563,
	[OID_gost2012Digest256] = 571,
	[OID_gost2012Digest512] = 579,
	[OID_gost2012Signature256] = 587,
	[OID_gost2012Signature512] = 595,
	[OID_gostTC26Sign256A] = 603,
	[OID_gostTC26Sign256B] = 612,
	[OID_gostTC26Sign256C] = 621,
	[OID_gostTC26Sign256D] = 630,
	[OID_gostTC26Sign512A] = 639,
	[OID_gostTC26Sign512B] = 648,
	[OID_gostTC26Sign512C] = 657,
	[OID_sm2] = 666,
	[OID_sm3] = 674,
	[OID_SM2_with_SM3] = 682,
	[OID_sm3WithRSAEncryption] = 690,
	[OID_TPMLoadableKey] = 698,
	[OID_TPMImportableKey] = 704,
	[OID_TPMSealedData] = 710,
	[OID_sha3_256] = 716,
	[OID_sha3_384] = 725,
	[OID_sha3_512] = 734,
	[OID_shake128] = 743,
	[OID_shake256] = 752,
	[OID_id_ecdsa_with_sha3_256] = 761,
	[OID_id_ecdsa_with_sha3_384] = 770,
	[OID_id_ecdsa_with_sha3_512] = 779,
	[OID_id_rsassa_pkcs1_v1_5_with_sha3_256] = 788,
	[OID_id_rsassa_pkcs1_v1_5_with_sha3_384] = 797,
	[OID_id_rsassa_pkcs1_v1_5_with_sha3_512] = 806,
	[OID_id_MLDSA44] = 815,
	[OID_id_MLDSA65] = 824,
	[OID_id_MLDSA87] = 833,
	[OID_id_MLDSA44_Ed25519] = 842,
	[OID_id_MLDSA65_Ed25519] = 853,
	[OID_id_MLDSA87_Ed448] = 864,
	[OID_id_SLHDSA_SHAKE_128S] = 875,
	[OID_id_SLHDSA_SHAKE_128F] = 884,
	[OID_id_SLHDSA_SHAKE_192S] = 893,
	[OID_id_SLHDSA_SHAKE_192F] = 902,
	[OID_id_SLHDSA_SHAKE_256S] = 911,
	[OID_id_SLHDSA_SHAKE_256F] = 920,
	[OID__NR] = 929
};

static const unsigned char oid_data[929] = {
	42, 134, 72, 206, 46, 4, 3, 	// id_dsa_with_sha1
	42, 134, 72, 206, 56, 4, 1, 	// id_dsa
	42, 134, 72, 206, 61, 2, 1, 	// id_ecPublicKey
	42, 134, 72, 206, 61, 3, 1, 1, 	// id_prime192v1
	42, 134, 72, 206, 61, 3, 1, 7, 	// id_prime256v1
	42, 134, 72, 206, 61, 4, 1, 	// id_ecdsa_with_sha1
	42, 134, 72, 206, 61, 4, 3, 1, 	// id_ecdsa_with_sha224
	42, 134, 72, 206, 61, 4, 3, 2, 	// id_ecdsa_with_sha256
	42, 134, 72, 206, 61, 4, 3, 3, 	// id_ecdsa_with_sha384
	42, 134, 72, 206, 61, 4, 3, 4, 	// id_ecdsa_with_sha512
	42, 134, 72, 134, 247, 13, 1, 1, 1, 	// rsaEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 5, 	// sha1WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 11, 	// sha256WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 12, 	// sha384WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 13, 	// sha512WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 14, 	// sha224WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 7, 1, 	// data
	42, 134, 72, 134, 247, 13, 1, 7, 2, 	// signed_data
	42, 134, 72, 134, 247, 13, 1, 9, 1, 	// email_address
	42, 134, 72, 134, 247, 13, 1, 9, 3, 	// contentType
	42, 134, 72, 134, 247, 13, 1, 9, 4, 	// messageDigest
	42, 134, 72, 134, 247, 13, 1, 9, 5, 	// signingTime
	42, 134, 72, 134, 247, 13, 1, 9, 15, 	// smimeCapabilites
	42, 134, 72, 134, 247, 13, 1, 9, 16, 2, 11, 	// smimeAuthenticatedAttrs
	42, 134, 72, 130, 247, 18, 1, 2, 2, 	// mskrb5
	42, 134, 72, 134, 247, 18, 1, 2, 2, 	// krb5
	42, 134, 72, 134, 247, 18, 1, 2, 2, 3, 	// krb5u2u
	43, 6, 1, 4, 1, 130, 55, 2, 1, 4, 	// msIndirectData
	43, 6, 1, 4, 1, 130, 55, 2, 1, 11, 	// msStatementType
	43, 6, 1, 4, 1, 130, 55, 2, 1, 12, 	// msSpOpusInfo
	43, 6, 1, 4, 1, 130, 55, 2, 1, 15, 	// msPeImageDataObjId
	43, 6, 1, 4, 1, 130, 55, 2, 1, 21, 	// msIndividualSPKeyPurpose
	43, 6, 1, 4, 1, 130, 55, 16, 4, 	// msOutlookExpress
	43, 6, 1, 4, 1, 130, 55, 2, 2, 10, 	// ntlmssp
	43, 6, 1, 4, 1, 130, 55, 2, 2, 30, 	// negoex
	43, 6, 1, 5, 5, 2, 	// spnego
	43, 6, 1, 5, 2, 5, 	// IAKerb
	43, 5, 1, 5, 2, 7, 	// PKU2U
	43, 6, 1, 5, 5, 14, 	// Scram
	43, 6, 1, 5, 5, 7, 1, 1, 	// certAuthInfoAccess
	43, 14, 3, 2, 26, 	// sha1
	43, 129, 4, 0, 34, 	// id_ansip384r1
	43, 129, 4, 0, 35, 	// id_ansip521r1
	96, 134, 72, 1, 101, 3, 4, 2, 1, 	// sha256
	96, 134, 72, 1, 101, 3, 4, 2, 2, 	// sha384
	96, 134, 72, 1, 101, 3, 4, 2, 3, 	// sha512
	96, 134, 72, 1, 101, 3, 4, 2, 4, 	// sha224
	85, 4, 3, 	// commonName
	85, 4, 4, 	// surname
	85, 4, 6, 	// countryName
	85, 4, 7, 	// locality
	85, 4, 8, 	// stateOrProvinceName
	85, 4, 10, 	// organizationName
	85, 4, 11, 	// organizationUnitName
	85, 4, 12, 	// title
	85, 4, 13, 	// description
	85, 4, 41, 	// name
	85, 4, 42, 	// givenName
	85, 4, 43, 	// initials
	85, 4, 44, 	// generationalQualifier
	85, 29, 14, 	// subjectKeyIdentifier
	85, 29, 15, 	// keyUsage
	85, 29, 17, 	// subjectAltName
	85, 29, 18, 	// issuerAltName
	85, 29, 19, 	// basicConstraints
	85, 29, 31, 	// crlDistributionPoints
	85, 29, 32, 	// certPolicies
	85, 29, 35, 	// authorityKeyIdentifier
	85, 29, 37, 	// extKeyUsage
	85, 29, 37, 0, 	// anyExtendedKeyUsage
	43, 6, 1, 5, 5, 7, 3, 1, 	// id_kp_serverAuth
	43, 6, 1, 5, 5, 7, 3, 2, 	// id_kp_clientAuth
	43, 6, 1, 5, 5, 7, 3, 3, 	// id_kp_codeSigning
	43, 6, 1, 5, 5, 7, 3, 4, 	// id_kp_emailProtection
	43, 6, 1, 5, 5, 7, 3, 8, 	// id_kp_timeStamping
	43, 6, 1, 5, 5, 7, 3, 9, 	// id_kp_OCSPSigning
	43, 6, 1, 4, 1, 146, 8, 16, 1, 2, 	// id_kp_ModuleSigning
	42, 133, 112, 43, 14, 2, 	// NetlogonMechanism
	42, 133, 112, 43, 14, 3, 	// appleLocalKdcSupported
	42, 133, 3, 2, 2, 35, 1, 	// gostCPSignA
	42, 133, 3, 2, 2, 35, 2, 	// gostCPSignB
	42, 133, 3, 2, 2, 35, 3, 	// gostCPSignC
	42, 133, 3, 7, 1, 1, 1, 1, 	// gost2012PKey256
	42, 133, 3, 7, 1, 1, 1, 2, 	// gost2012PKey512
	42, 133, 3, 7, 1, 1, 2, 2, 	// gost2012Digest256
	42, 133, 3, 7, 1, 1, 2, 3, 	// gost2012Digest512
	42, 133, 3, 7, 1, 1, 3, 2, 	// gost2012Signature256
	42, 133, 3, 7, 1, 1, 3, 3, 	// gost2012Signature512
	42, 133, 3, 7, 1, 2, 1, 1, 1, 	// gostTC26Sign256A
	42, 133, 3, 7, 1, 2, 1, 1, 2, 	// gostTC26Sign256B
	42, 133, 3, 7, 1, 2, 1, 1, 3, 	// gostTC26Sign256C
	42, 133, 3, 7, 1, 2, 1, 1, 4, 	// gostTC26Sign256D
	42, 133, 3, 7, 1, 2, 1, 2, 1, 	// gostTC26Sign512A
	42, 133, 3, 7, 1, 2, 1, 2, 2, 	// gostTC26Sign512B
	42, 133, 3, 7, 1, 2, 1, 2, 3, 	// gostTC26Sign512C
	42, 129, 28, 207, 85, 1, 130, 45, 	// sm2
	42, 129, 28, 207, 85, 1, 131, 17, 	// sm3
	42, 129, 28, 207, 85, 1, 131, 117, 	// SM2_with_SM3
	42, 129, 28, 207, 85, 1, 131, 120, 	// sm3WithRSAEncryption
	103, 129, 5, 10, 1, 3, 	// TPMLoadableKey
	103, 129, 5, 10, 1, 4, 	// TPMImportableKey
	103, 129, 5, 10, 1, 5, 	// TPMSealedData
	96, 134, 72, 1, 101, 3, 4, 2, 8, 	// sha3_256
	96, 134, 72, 1, 101, 3, 4, 2, 9, 	// sha3_384
	96, 134, 72, 1, 101, 3, 4, 2, 10, 	// sha3_512
	96, 134, 72, 1, 101, 3, 4, 2, 11, 	// shake128
	96, 134, 72, 1, 101, 3, 4, 2, 12, 	// shake256
	96, 134, 72, 1, 101, 3, 4, 3, 10, 	// id_ecdsa_with_sha3_256
	96, 134, 72, 1, 101, 3, 4, 3, 11, 	// id_ecdsa_with_sha3_384
	96, 134, 72, 1, 101, 3, 4, 3, 12, 	// id_ecdsa_with_sha3_512
	96, 134, 72, 1, 101, 3, 4, 3, 14, 	// id_rsassa_pkcs1_v1_5_with_sha3_256
	96, 134, 72, 1, 101, 3, 4, 3, 15, 	// id_rsassa_pkcs1_v1_5_with_sha3_384
	96, 134, 72, 1, 101, 3, 4, 3, 16, 	// id_rsassa_pkcs1_v1_5_with_sha3_512
	96, 134, 72, 1, 101, 3, 4, 3, 17, 	// id_MLDSA44
	96, 134, 72, 1, 101, 3, 4, 3, 18, 	// id_MLDSA65
	96, 134, 72, 1, 101, 3, 4, 3, 19, 	// id_MLDSA87
	96, 134, 72, 1, 134, 250, 107, 80, 9, 1, 2, 	// id_MLDSA44_Ed25519
	96, 134, 72, 1, 134, 250, 107, 80, 9, 1, 11, 	// id_MLDSA65_Ed25519
	96, 134, 72, 1, 134, 250, 107, 80, 9, 1, 14, 	// id_MLDSA87_Ed448
	96, 134, 72, 1, 101, 3, 4, 3, 26, 	// id_SLHDSA_SHAKE_128S
	96, 134, 72, 1, 101, 3, 4, 3, 27, 	// id_SLHDSA_SHAKE_128F
	96, 134, 72, 1, 101, 3, 4, 3, 28, 	// id_SLHDSA_SHAKE_192S
	96, 134, 72, 1, 101, 3, 4, 3, 29, 	// id_SLHDSA_SHAKE_192F
	96, 134, 72, 1, 101, 3, 4, 3, 30, 	// id_SLHDSA_SHAKE_256S
	96, 134, 72, 1, 101, 3, 4, 3, 31, 	// id_SLHDSA_SHAKE_256F
};

static const struct {
	unsigned char hash;
	enum OID oid : 8;
} oid_search_table[OID__NR] = {
	[  0] = {   3, OID_id_rsassa_pkcs1_v1_5_with_sha3_256  }, // 60864801650304030e
	[  1] = {  10, OID_title                               }, // 55040c
	[  2] = {  11, OID_spnego                              }, // 2b0601050502
	[  3] = {  11, OID_IAKerb                              }, // 2b0601050205
	[  4] = {  13, OID_id_ansip384r1                       }, // 2b81040022
	[  5] = {  19, OID_gostTC26Sign512C                    }, // 2a8503070102010203
	[  6] = {  19, OID_gostTC26Sign256D                    }, // 2a8503070102010104
	[  7] = {  23, OID_issuerAltName                       }, // 551d12
	[  8] = {  23, OID_initials                            }, // 55042b
	[  9] = {  26, OID_id_SLHDSA_SHAKE_192F                }, // 60864801650304031d
	[ 10] = {  26, OID_id_MLDSA65_Ed25519                  }, // 6086480186fa6b5009010b
	[ 11] = {  31, OID_id_kp_timeStamping                  }, // 2b06010505070308
	[ 12] = {  32, OID_id_dsa_with_sha1                    }, // 2a8648ce2e0403
	[ 13] = {  35, OID_contentType                         }, // 2a864886f70d010903
	[ 14] = {  35, OID_sha256WithRSAEncryption             }, // 2a864886f70d01010b
	[ 15] = {  36, OID_authorityKeyIdentifier              }, // 551d23
	[ 16] = {  37, OID_description                         }, // 55040d
	[ 17] = {  39, OID_id_kp_serverAuth                    }, // 2b06010505070301
	[ 18] = {  43, OID_id_dsa                              }, // 2a8648ce380401
	[ 19] = {  44, OID_id_ansip521r1                       }, // 2b81040023
	[ 20] = {  44, OID_PKU2U                               }, // 2b0501050207
	[ 21] = {  44, OID_krb5u2u                             }, // 2a864886f71201020203
	[ 22] = {  49, OID_id_ecdsa_with_sha224                }, // 2a8648ce3d040301
	[ 23] = {  50, OID_id_MLDSA44_Ed25519                  }, // 6086480186fa6b50090102
	[ 24] = {  51, OID_msIndividualSPKeyPurpose            }, // 2b060104018237020115
	[ 25] = {  52, OID_SM2_with_SM3                        }, // 2a811ccf55018375
	[ 26] = {  54, OID_basicConstraints                    }, // 551d13
	[ 27] = {  54, OID_generationalQualifier               }, // 55042c
	[ 28] = {  59, OID_id_SLHDSA_SHAKE_192S                }, // 60864801650304031c
	[ 29] = {  60, OID_gostCPSignA                         }, // 2a850302022301
	[ 30] = {  60, OID_id_kp_OCSPSigning                   }, // 2b06010505070309
	[ 31] = {  64, OID_TPMLoadableKey                      }, // 6781050a0103
	[ 32] = {  64, OID_krb5                                }, // 2a864886f712010202
	[ 33] = {  64, OID_signed_data                         }, // 2a864886f70d010702
	[ 34] = {  65, OID_id_rsassa_pkcs1_v1_5_with_sha3_512  }, // 608648016503040310
	[ 35] = {  70, OID_id_kp_clientAuth                    }, // 2b06010505070302
	[ 36] = {  76, OID_id_prime192v1                       }, // 2a8648ce3d030101
	[ 37] = {  77, OID_countryName                         }, // 550406
	[ 38] = {  77, OID_id_ecdsa_with_sha1                  }, // 2a8648ce3d0401
	[ 39] = {  83, OID_sha256                              }, // 608648016503040201
	[ 40] = {  84, OID_sm2                                 }, // 2a811ccf5501822d
	[ 41] = {  85, OID_smimeCapabilites                    }, // 2a864886f70d01090f
	[ 42] = {  87, OID_sha1                                }, // 2b0e03021a
	[ 43] = {  88, OID_sha3_384                            }, // 608648016503040209
	[ 44] = {  92, OID_id_SLHDSA_SHAKE_256F                }, // 60864801650304031f
	[ 45] = {  93, OID_gostCPSignB                         }, // 2a850302022302
	[ 46] = {  97, OID_email_address                       }, // 2a864886f70d010901
	[ 47] = {  98, OID_id_rsassa_pkcs1_v1_5_with_sha3_384  }, // 60864801650304030f
	[ 48] = { 105, OID_anyExtendedKeyUsage                 }, // 551d2500
	[ 49] = { 106, OID_extKeyUsage                         }, // 551d25
	[ 50] = { 106, OID_msPeImageDataObjId                  }, // 2b06010401823702010f
	[ 51] = { 110, OID_locality                            }, // 550407
	[ 52] = { 112, OID_id_kp_ModuleSigning                 }, // 2b060104019208100102
	[ 53] = { 120, OID_negoex                              }, // 2b06010401823702021e
	[ 54] = { 121, OID_id_kp_codeSigning                   }, // 2b06010505070303
	[ 55] = { 123, OID_sha3_256                            }, // 608648016503040208
	[ 56] = { 124, OID_gost2012PKey256                     }, // 2a85030701010101
	[ 57] = { 125, OID_id_SLHDSA_SHAKE_256S                }, // 60864801650304031e
	[ 58] = { 126, OID_gostCPSignC                         }, // 2a850302022303
	[ 59] = { 126, OID_rsaEncryption                       }, // 2a864886f70d010101
	[ 60] = { 130, OID_TPMSealedData                       }, // 6781050a0105
	[ 61] = { 132, OID_smimeAuthenticatedAttrs             }, // 2a864886f70d010910020b
	[ 62] = { 134, OID_Scram                               }, // 2b060105050e
	[ 63] = { 134, OID_id_ecdsa_with_sha3_256              }, // 60864801650304030a
	[ 64] = { 134, OID_shake128                            }, // 60864801650304020b
	[ 65] = { 142, OID_id_ecPublicKey                      }, // 2a8648ce3d0201
	[ 66] = { 142, OID_sha224WithRSAEncryption             }, // 2a864886f70d01010e
	[ 67] = { 143, OID_stateOrProvinceName                 }, // 550408
	[ 68] = { 143, OID_id_MLDSA65                          }, // 608648016503040312
	[ 69] = { 145, OID_sm3WithRSAEncryption                }, // 2a811ccf55018378
	[ 70] = { 146, OID_subjectKeyIdentifier                }, // 551d0e
	[ 71] = { 150, OID_id_ecdsa_with_sha512                }, // 2a8648ce3d040304
	[ 72] = { 150, OID_id_prime256v1                       }, // 2a8648ce3d030107
	[ 73] = { 152, OID_id_kp_emailProtection               }, // 2b06010505070304
	[ 74] = { 157, OID_gost2012PKey512                     }, // 2a85030701010102
	[ 75] = { 157, OID_sha512                              }, // 608648016503040203
	[ 76] = { 160, OID_data                                }, // 2a864886f70d010701
	[ 77] = { 160, OID_id_MLDSA44                          }, // 608648016503040311
	[ 78] = { 161, OID_crlDistributionPoints               }, // 551d1f
	[ 79] = { 161, OID_TPMImportableKey                    }, // 6781050a0104
	[ 80] = { 173, OID_msOutlookExpress                    }, // 2b0601040182371004
	[ 81] = { 178, OID_sha384                              }, // 608648016503040202
	[ 82] = { 179, OID_keyUsage                            }, // 551d0f
	[ 83] = { 179, OID_NetlogonMechanism                   }, // 2a85702b0e02
	[ 84] = { 185, OID_sha3_512                            }, // 60864801650304020a
	[ 85] = { 190, OID_gost2012Digest256                   }, // 2a85030701010202
	[ 86] = { 191, OID_gostTC26Sign256A                    }, // 2a8503070102010101
	[ 87] = { 191, OID_id_MLDSA87_Ed448                    }, // 6086480186fa6b5009010e
	[ 88] = { 195, OID_mskrb5                              }, // 2a864882f712010202
	[ 89] = { 196, OID_id_ecdsa_with_sha3_512              }, // 60864801650304030c
	[ 90] = { 198, OID_certPolicies                        }, // 551d20
	[ 91] = { 200, OID_msSpOpusInfo                        }, // 2b06010401823702010c
	[ 92] = { 201, OID_organizationName                    }, // 55040a
	[ 93] = { 204, OID_messageDigest                       }, // 2a864886f70d010904
	[ 94] = { 204, OID_sha384WithRSAEncryption             }, // 2a864886f70d01010c
	[ 95] = { 208, OID_id_ecdsa_with_sha256                }, // 2a8648ce3d040302
	[ 96] = { 208, OID_gostTC26Sign512A                    }, // 2a8503070102010201
	[ 97] = { 208, OID_gostTC26Sign256B                    }, // 2a8503070102010102
	[ 98] = { 212, OID_name                                }, // 550429
	[ 99] = { 213, OID_commonName                          }, // 550403
	[100] = { 213, OID_sm3                                 }, // 2a811ccf55018311
	[101] = { 217, OID_id_SLHDSA_SHAKE_128F                }, // 60864801650304031b
	[102] = { 223, OID_gost2012Signature256                }, // 2a85030701010302
	[103] = { 223, OID_gost2012Digest512                   }, // 2a85030701010203
	[104] = { 226, OID_sha1WithRSAEncryption               }, // 2a864886f70d010105
	[105] = { 228, OID_certAuthInfoAccess                  }, // 2b06010505070101
	[106] = { 231, OID_id_ecdsa_with_sha3_384              }, // 60864801650304030b
	[107] = { 231, OID_shake256                            }, // 60864801650304020c
	[108] = { 231, OID_ntlmssp                             }, // 2b06010401823702020a
	[109] = { 231, OID_msStatementType                     }, // 2b06010401823702010b
	[110] = { 234, OID_organizationUnitName                }, // 55040b
	[111] = { 236, OID_appleLocalKdcSupported              }, // 2a85702b0e03
	[112] = { 237, OID_signingTime                         }, // 2a864886f70d010905
	[113] = { 237, OID_sha512WithRSAEncryption             }, // 2a864886f70d01010d
	[114] = { 238, OID_id_MLDSA87                          }, // 608648016503040313
	[115] = { 240, OID_gost2012Signature512                }, // 2a85030701010303
	[116] = { 241, OID_gostTC26Sign512B                    }, // 2a8503070102010202
	[117] = { 241, OID_gostTC26Sign256C                    }, // 2a8503070102010103
	[118] = { 244, OID_surname                             }, // 550404
	[119] = { 245, OID_subjectAltName                      }, // 551d11
	[120] = { 245, OID_givenName                           }, // 55042a
	[121] = { 247, OID_id_ecdsa_with_sha384                }, // 2a8648ce3d040303
	[122] = { 248, OID_id_SLHDSA_SHAKE_128S                }, // 60864801650304031a
	[123] = { 252, OID_sha224                              }, // 608648016503040204
	[124] = { 255, OID_msIndirectData                      }, // 2b060104018237020104
};
// clang-format on
