/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for pkcs7_aa
 */
#pragma once
#include "asn1_encoder.h"
#include "asn1_decoder.h"

// clang-format off
extern const struct asn1_encoder pkcs7_aa_encoder;
extern const struct asn1_decoder pkcs7_aa_decoder;

extern int pkcs7_separate_aa_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int pkcs7_separate_aa(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int pkcs7_separate_aa_OID_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int pkcs7_separate_aa_OID(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int pkcs7_separate_aa_continue_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int pkcs7_separate_aa_continue(void *, size_t, unsigned char, const uint8_t *, size_t);
// clang-format on
