
/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_slhdsa_privkey
 */
#include "asn1_ber_bytecode.h"
#include "x509_slhdsa_privkey_asn1.h"

// clang-format off

enum x509_slhdsa_privkey_actions {
	ACT_x509_slhdsa_private_key = 0,
	NR__x509_slhdsa_privkey_actions = 1
};

static const asn1_action_t x509_slhdsa_privkey_action_table[NR__x509_slhdsa_privkey_actions] = {
	[   0] = x509_slhdsa_private_key,
};

static const asn1_action_enc_t x509_slhdsa_privkey_action_table_enc[NR__x509_slhdsa_privkey_actions] = {
	[   0] = x509_slhdsa_private_key_enc,
};

static const unsigned char x509_slhdsa_privkey_machine[] = {
	// SignaturePrivateKey
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	[   2] =  ASN1_OP_MATCH_ACT,		// privateKey
	[   3] =  _tag(UNIV, PRIM, BTS),
	[   4] =  _action(ACT_x509_slhdsa_private_key),
	[   5] = ASN1_OP_END_SEQ,
	[   6] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder x509_slhdsa_privkey_decoder = {
	.machine = x509_slhdsa_privkey_machine,
	.machlen = sizeof(x509_slhdsa_privkey_machine),
	.actions = x509_slhdsa_privkey_action_table,
};

const struct asn1_encoder x509_slhdsa_privkey_encoder = {
	.machine = x509_slhdsa_privkey_machine,
	.machlen = sizeof(x509_slhdsa_privkey_machine),
	.actions = x509_slhdsa_privkey_action_table_enc,
};

// clang-format on
