/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_san
 */
#pragma once
#include "asn1_decoder.h"

extern const struct asn1_decoder x509_san_decoder;

extern int x509_extract_name_segment(void *, size_t, unsigned char,
				     const uint8_t *, size_t);
extern int x509_note_OID(void *, size_t, unsigned char, const uint8_t *,
			 size_t);
extern int x509_san_dns(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int x509_san_ip(void *, size_t, unsigned char, const uint8_t *, size_t);
