/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_mldsa_privkey
 */
#pragma once
#include "asn1_encoder.h"
#include "asn1_decoder.h"

// clang-format off
extern const struct lc_asn1_encoder lc_x509_mldsa_privkey_encoder;
extern const struct lc_asn1_decoder lc_x509_mldsa_privkey_decoder;

extern int lc_x509_mldsa_private_key_expanded_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_mldsa_private_key_expanded(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_x509_mldsa_private_key_seed_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_mldsa_private_key_seed(void *, size_t, unsigned char, const uint8_t *, size_t);
// clang-format on
