/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_basic_constraints
 */
#include "asn1_ber_bytecode.h"
#include "x509_basic_constraints.asn1.h"

enum x509_basic_constraints_actions {
	ACT_x509_basic_constraints_ca = 0,
	ACT_x509_basic_constraints_pathlen = 1,
	NR__x509_basic_constraints_actions = 2
};

static const asn1_action_t x509_basic_constraints_action_table
	[NR__x509_basic_constraints_actions] = {
		[0] = x509_basic_constraints_ca,
		[1] = x509_basic_constraints_pathlen,
	};

static const unsigned char x509_basic_constraints_machine[] = {
	// BasicConstraints
	[0] = ASN1_OP_MATCH,
	[1] = _tag(UNIV, CONS, SEQ),
	[2] = ASN1_OP_MATCH_ACT_OR_SKIP, // cA
	[3] = _tag(UNIV, PRIM, BOOL),
	[4] = _action(ACT_x509_basic_constraints_ca),
	[5] = ASN1_OP_MATCH_ACT_OR_SKIP, // pathLenConstraint
	[6] = _tag(UNIV, PRIM, INT),
	[7] = _action(ACT_x509_basic_constraints_pathlen),
	[8] = ASN1_OP_END_SEQ,
	[9] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder x509_basic_constraints_decoder = {
	.machine = x509_basic_constraints_machine,
	.machlen = sizeof(x509_basic_constraints_machine),
	.actions = x509_basic_constraints_action_table,
};
