/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_keyusage
 */
#pragma once
#include "asn1_decoder.h"

extern const struct asn1_decoder x509_keyusage_decoder;

extern int x509_key_usage(void *, size_t, unsigned char, const uint8_t *,
			  size_t);
