/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_san
 */
#pragma once
#include "asn1_encoder.h"
#include "asn1_decoder.h"

// clang-format off
extern const struct lc_asn1_encoder lc_x509_san_encoder;
extern const struct lc_asn1_decoder lc_x509_san_decoder;

extern int lc_x509_extract_name_segment_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_extract_name_segment(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_x509_san_OID_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_san_OID(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_x509_san_dns_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_san_dns(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_x509_san_email_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_san_email(void *, size_t, unsigned char, const uint8_t *, size_t);
extern int lc_x509_san_ip_enc(void *, uint8_t *, size_t *, uint8_t *);
extern int lc_x509_san_ip(void *, size_t, unsigned char, const uint8_t *, size_t);
// clang-format on
