
/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_san
 */
#include "asn1_ber_bytecode.h"
#include "x509_san_asn1.h"

// clang-format off

enum x509_san_actions {
	ACT_lc_x509_extract_name_segment = 0,
	ACT_lc_x509_san_OID = 1,
	ACT_lc_x509_san_dns = 2,
	ACT_lc_x509_san_email = 3,
	ACT_lc_x509_san_ip = 4,
	NR__x509_san_actions = 5
};

static const asn1_action_t x509_san_action_table[NR__x509_san_actions] = {
	[   0] = lc_x509_extract_name_segment,
	[   1] = lc_x509_san_OID,
	[   2] = lc_x509_san_dns,
	[   3] = lc_x509_san_email,
	[   4] = lc_x509_san_ip,
};

static const asn1_action_enc_t x509_san_action_table_enc[NR__x509_san_actions] = {
	[   0] = lc_x509_extract_name_segment_enc,
	[   1] = lc_x509_san_OID_enc,
	[   2] = lc_x509_san_dns_enc,
	[   3] = lc_x509_san_email_enc,
	[   4] = lc_x509_san_ip_enc,
};

static const unsigned char x509_san_machine[] = {
	// SubjectAltName
	// GeneralNames
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	// GeneralName
	// OtherName
	[   2] =  ASN1_OP_MATCH_JUMP_OR_SKIP,		// otherName
	[   3] =  _tagn(CONT, CONS,  0),
	[   4] =  _jump_target(31),		// --> OtherName
	[   5] =  ASN1_OP_COND_MATCH_ACT_OR_SKIP,		// rfc822Name
	[   6] =  _tagn(CONT, PRIM,  1),
	[   7] =  _action(ACT_lc_x509_san_email),
	[   8] =  ASN1_OP_COND_MATCH_ACT_OR_SKIP,		// dNSName
	[   9] =  _tagn(CONT, PRIM,  2),
	[  10] =  _action(ACT_lc_x509_san_dns),
	[  11] =  ASN1_OP_COND_MATCH_JUMP_OR_SKIP,		// x400Address
	[  12] =  _tagn(CONT, CONS,  3),
	[  13] =  _jump_target(39),
	[  14] =  ASN1_OP_COND_MATCH_JUMP_OR_SKIP,		// directoryName
	[  15] =  _tagn(CONT, CONS,  4),
	[  16] =  _jump_target(42),
	// EDIPartyName
	[  17] =  ASN1_OP_COND_MATCH_JUMP_OR_SKIP,		// ediPartyName
	[  18] =  _tagn(CONT, CONS,  5),
	[  19] =  _jump_target(60),		// --> EDIPartyName
	[  20] =  ASN1_OP_COND_MATCH_OR_SKIP,		// uniformResourceIdentifier
	[  21] =  _tagn(CONT, PRIM,  6),
	[  22] =  ASN1_OP_COND_MATCH_ACT_OR_SKIP,		// iPAddress
	[  23] =  _tagn(CONT, PRIM,  7),
	[  24] =  _action(ACT_lc_x509_san_ip),
	[  25] =  ASN1_OP_COND_MATCH_OR_SKIP,		// registeredID
	[  26] =  _tagn(CONT, PRIM,  8),
	[  27] =  ASN1_OP_COND_FAIL,
	[  28] = ASN1_OP_END_SEQ_OF,
	[  29] = _jump_target(2),
	[  30] = ASN1_OP_COMPLETE,

	[  31] =  ASN1_OP_MATCH,		// type-id
	[  32] =  _tag(UNIV, PRIM, OID),
	[  33] =  ASN1_OP_MATCH,		// value
	[  34] =  _tagn(CONT, CONS,  0),
	[  35] =   ASN1_OP_MATCH_ANY,		// value
	[  36] =  ASN1_OP_END_SEQ,
	[  37] = ASN1_OP_END_SEQ,
	[  38] = ASN1_OP_RETURN,

	[  39] =  ASN1_OP_MATCH_ANY,		// x400Address
	[  40] = ASN1_OP_END_SEQ,
	[  41] = ASN1_OP_RETURN,

	// Name
	[  42] =  ASN1_OP_MATCH,
	[  43] =  _tag(UNIV, CONS, SEQ),
	// RelativeDistinguishedName
	[  44] =   ASN1_OP_MATCH,
	[  45] =   _tag(UNIV, CONS, SET),
	// AttributeValueAssertion
	[  46] =    ASN1_OP_MATCH,
	[  47] =    _tag(UNIV, CONS, SEQ),
	[  48] =     ASN1_OP_MATCH_ACT,		// attributeType
	[  49] =     _tag(UNIV, PRIM, OID),
	[  50] =     _action(ACT_lc_x509_san_OID),
	[  51] =     ASN1_OP_MATCH_ANY_ACT,		// attributeValue
	[  52] =     _action(ACT_lc_x509_extract_name_segment),
	[  53] =    ASN1_OP_END_SEQ,
	[  54] =   ASN1_OP_END_SET_OF,
	[  55] =   _jump_target(46),
	[  56] =  ASN1_OP_END_SEQ_OF,
	[  57] =  _jump_target(44),
	[  58] = ASN1_OP_END_SEQ,
	[  59] = ASN1_OP_RETURN,

	[  60] =  ASN1_OP_MATCH_JUMP_OR_SKIP,		// nameAssigner
	[  61] =  _tagn(CONT, CONS,  0),
	[  62] =  _jump_target(69),
	[  63] =  ASN1_OP_MATCH,		// partyName
	[  64] =  _tagn(CONT, CONS,  1),
	[  65] =   ASN1_OP_MATCH_ANY,		// partyName
	[  66] =  ASN1_OP_END_SEQ,
	[  67] = ASN1_OP_END_SEQ,
	[  68] = ASN1_OP_RETURN,

	[  69] =  ASN1_OP_MATCH_ANY,		// nameAssigner
	[  70] = ASN1_OP_END_SEQ,
	[  71] = ASN1_OP_RETURN,
};

const struct lc_asn1_decoder lc_x509_san_decoder = {
	.machine = x509_san_machine,
	.machlen = sizeof(x509_san_machine),
	.actions = x509_san_action_table,
};

const struct lc_asn1_encoder lc_x509_san_encoder = {
	.machine = x509_san_machine,
	.machlen = sizeof(x509_san_machine),
	.actions = x509_san_action_table_enc,
};

// clang-format on
